#关闭Thymeleaf缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    name: mrhill
    url: jdbc:mysql://127.0.0.1:3306/mrhill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '!QAZxdr5'
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true


server:
  port: 9000
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tlp.mrhill.model
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

